version: '3'

services:
  frontend:
    image: atts_frontend
    restart: always
    build:
      context: ./front
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
        REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
        REACT_APP_KEYCLOAK_URL: ${REACT_APP_KEYCLOAK_URL}
        REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
        REACT_APP_KEYCLOAK_RESOURCE: ${REACT_APP_KEYCLOAK_RESOURCE}
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    container_name: my-atts-frontend
    depends_on:
      backend:
        condition: service_started
      keycloak:
        condition: service_started

  backend:
    image: atts_backend
    build:
      context: ./msystem
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOACK_CLIENT_SECRET=${KEYCLOACK_CLIENT_SECRET}
      - FE_URL=${FE_URL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${EMAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DB_URL=${DB_URL}
    restart: always
    ports:
      - "${BE_PORT}:8082"
    container_name: my-atts-backend
    depends_on:
      keycloak:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes:
      - be-vol:/app/invoices

  keycloak:
    build:
      dockerfile: Dockerfile.keycloak
      args:
        KEYCLOAK_VERSION: 24.0
    container_name: keycloak
    restart: always
    ports:
      - 8080:8443
    volumes:
      - /root/atts_deploy/atts/factureapi.fr_ssl_certificate.cer:/etc/x509/https/tls.crt
      - /root/atts_deploy/atts/_.factureapi.fr_private_key.key:/etc/x509/https/tls.key
      #- ./realms:/opt/keycloak/data/import:ro
      - keycloak-vol:/opt/keycloak/data
    environment:
      #- JAVA_OPTS_KC_HEAP="-XX:MaxHeapFreeRatio=30 -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=65"
      - KEYCLOAK_ADMIN=keycloak_admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
      # - KC_HOSTNAME_STRICT=false
      # - KC_HOSTNAME=localhost
      # - DB_URL_HOST=mysql
      # - DB_SCHEMA=keycloak
      # - DB_USERNAME=keycloak
      # - DB_PASSWORD=keycloak
    #command: start-dev --import-realm
    command: start-dev
    #command: start --optimized

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'atts'
      MYSQL_USER: 'atts'
      MYSQL_PASSWORD: 'atts'
      MYSQL_ROOT_PASSWORD: 'root'
    logging:   # Add logging configuration here
      driver: json-file   # Use json-file logging driver
      options:
        max-size: "10m"    # maximum log file size before rotation
        max-file: "3"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      # - db-vol:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: mysqladmin --slient ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}
      start_period: 1m
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      device: ./data/db_data
      o: 'bind'
  be-vol:
    driver: local
    driver_opts:
      type: none
      device: ./data/be_data
      o: bind
  keycloak-vol:
    driver: local
    driver_opts:
      type: none
      device: ./data/keycloak_data
      o: bind
