server:
  port: 8082
keycloak:
  realm: atts
  url: http://localhost:8080
  client-id: atts-application
  client-secret: OkidE95rHmfnIvRI6ZWrAlO817BozgRl
frontend:
  host: http://localhost:3000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    #password attsionos12!
    username: testatts12@gmail.com
    password: evxzqqiffikmecce
#    host: smtp.ionos.fr
#    port: 587
#    username: invoice@atts.fr
#    password: Invoice2022
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/atts
    username: atts
    password: atts
