server:
  port: 8082
keycloak:
  client-id: atts-application
spring:
  mail:
    default-encoding: UTF-8
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  datasource:
    username: atts
    password: atts
  profiles:
    active: dev
