keycloak:
  realm: atts-development
  url: https://v1.factureapi.fr:8080
  client-secret: QkMx6TaM8UA0aPt5xOZTzOTIPN59OZk6
frontend:
  host: http://localhost:3000

spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
             enable: true
             required: true
#    host: smtp.ionos.fr
#    port: 465
#    username: invoice@atts.fr
#    password: Invoice2022
    host: smtp.gmail.com
    port: 587
    username: testatts12@gmail.com
    password: evxzqqiffikmecce
    smtp:
      auth: true
      ssl:
        enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/atts
